### ISSUE TITLE
No launch files in the released packages

### ISSUE THREAD

**Issue by bmagyar** [RobotnikAutomation/summit_x_sim#2]
I installed the summit packages to test something in simulation but found that there are no launch files with your packages.
Releasing a package is pretty pointless **without install rules** in the CMakeLists.txt file. I suppose the generated debian packages are mostly empty?

See an example here for launch files:
https://github.com/pal-robotics/tiago_simulation/blob/indigo-devel/tiago_gazebo/CMakeLists.txt#L6

**Comment by JorgeArino** [comment]
Ok, thanks for the advice!

I've updated the CMakeList.txt on 867ddf8 . It will be released as soon as possible.

**Comment by bmagyar** [comment]
:+1:
